name: flutter_try
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  json_annotation: ^4.4.0
  google_sign_in: ^5.2.4
  firebase_dynamic_links: ^4.0.8
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  flutter_signin_button: ^2.0.0
  email_validator: ^2.0.1
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  scrolling_page_indicator: ^0.1.3
  carousel_slider: ^4.0.0
  english_words: ^4.0.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  getwidget: ^2.0.5
  intl: ^0.17.0
  multiple_select: ^0.1.22
  mask_text_input_formatter: ^2.1.0
  firebase_messaging: ^11.2.9
  flutter_local_notifications: ^9.4.0
  get: ^4.6.1

  image_picker: ^0.8.4+11




dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Logo.png"

flutter:
  assets:
    - assets/
    - assets/sdg/

  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/Ubuntu-Bold.ttf