name: flutter_try
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.18
  json_annotation: ^4.4.0

  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10


  cupertino_icons: ^1.0.2
  http: ^0.13.4
  scrolling_page_indicator: ^0.1.3
  carousel_slider: ^4.0.0
  english_words: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  build_runner: ^2.1.7



  flutter_lints: ^1.0.0


flutter:
  assets:
    - assets/
    - assets/sdg/

  uses-material-design: true
